modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory 
issueTrackerURL="" #optional
license="see license file"

[[mods]] #mandatory
modId="item_miner" #mandatory
logoFile="tg_icon.png"
logoBlur=false
version="${file.jarVersion}" #mandatory
displayName="Item Miner" #mandatory
authors="TelepathicGrunt"
description='''

'''

[[dependencies.item_miner]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5, 1.18.0)"

[[dependencies.item_miner]]
modId="forge"
mandatory=true
versionRange="[36.2.0,)"